# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "../out/nomad/centos-7.3.virtualbox.box"

  config.vm.provider "virtualbox" do |vb|
      vb.name = "nomad"
  end

end
